# -- Markup --
# These settings are required for the theme to function.

[goldmark]

[goldmark.extensions]
  definitionList = true

[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4
