[hugoVersion]
  extended = true
  min = "0.87.0"

[[imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[mounts]]
source = 'node_modules/loadicons/'
target = 'static/loadicons/'

[[mounts]]
source = 'node_modules/lit/'
target = 'static/lit/'

