[hugoVersion]
  extended = true
  min = "0.87.0"

[[imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss"

[[mounts]]
source = 'node_modules/@spectrum-css/vars/dist/'
target = 'static/@spectrum-css/vars/dist/'

[[mounts]]
source = 'node_modules/@spectrum-css/button/dist/'
target = 'static/@spectrum-css/button/dist/'

[[mounts]]
source = 'node_modules/@spectrum-css/page/dist/'
target = 'static/@spectrum-css/page/dist/'

[[mounts]]
source = 'node_modules/@spectrum-css/table/dist/'
target = 'static/@spectrum-css/table/dist/'

[[mounts]]
source = 'node_modules/@spectrum-css/icon/dist/'
target = 'static/@spectrum-css/icon/dist/'

[[mounts]]
source = 'node_modules/loadicons/'
target = 'static/loadicons'

