# use the setting below to set multiple docs directories.
# docSections = ["docs", "tutorials"]
docSections = [ "generals", "monsters", "svs", "reference" ]

uniqueHomePage = true # change to false to add sidebar to homepage

blogDir = "blog" # can be posts, blog e.t.c

repo = "https://github.com/lschierer/EvonyTKRTips"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
enableDarkMode = false # set to false to disable darkmode by default # user will still have the option to use dark mode
defaultLightingMode = "auto" # other possible values: "dark", "light"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 10

# show/hide line numbers by default. Switch to `true` if you'd rather have them on.
showLineNumbers = false

# By default the template will look for icons under the icons directory. In some situations you might wanna change that. edit the line below
# iconsPath = 'icons/'

otherSearchableFields = ["Tags", "Categories", "CustomField"] # As they appear in frontmatter

[taxonomy]
taxonomyCloud = ["tags"] # set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloudTitle = ["Tag Cloud"] # if used, must have same length as taxonomyCloud
taxonomyPageHeader = ["tags", "terms"] # set taxonomyPageHeader = [] to hide taxonomies on the page headers


# search
[search]
on = false
global = false # turn to `true` to enable global search

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false


# Site logo
[logo]
  lightMode = "images/ETKRTlogo.png"
  darkMode = "images/ETKRTlogo.png"

[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/onweru/compose/"

# optional
# attribution. Feel free to delete this
[author]
  name = "Luke Schierer"

# User interface configuration
[ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Show expand/collapse icon for sidebar sections.
sidebar_menu_foldable = true
# https://github.com/gohugoio/hugo/issues/8918#issuecomment-903314696
sidebar_cache_limit = 1
# Set to true to disable breadcrumb navigation.
breadcrumb_disable = true
taxonomy_breadcrumb_disable = true
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = false

[ui.feedback]
enable = false


