baseURL = 'https://evonytkrtips.netg/'
title = "Evony TKR Tips"
# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["congo"]

copyright = 'Luke Schierer'

github_repo = "https://github.com/lschierer/EvonyTKRTips.git"

# Language settings
enableRobotsTXT = true
disableBrowserError = true

disableKinds = []

navbar_logo = true

ignoreFiles = [ "(?:^|/)OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$", "content/en/docs/doc-contributor-tools" ]

timeout = "180s"

# Enable Git variables like commit, lastmod
enableGitInfo = true

# Norwegian ("no") is sometimes but not currently used for testing.
disableLanguages = ["no"]

[caches]
 [caches.assets]
  dir = ":cacheDir/_gen"
  maxAge = -1
 [caches.getcsv]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.getjson]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.images]
  dir = ":cacheDir/_images"
  maxAge = -1
 [caches.modules]
  dir = ":cacheDir/modules"
  maxAge = -1

[frontmatter]
  date = [":git", "date", ":filename", "publishDate", "lastmod"]

[sitemap]
  filename = "sitemap.xml"
  priority = 0.75

[services]
[services.googleAnalytics]
# Fake ID in support of [params.ui.feedback]. The real GA ID is set in the Netlify config.
id = "G-9KF1R3YFTZ"

