baseURL = 'https://evonytkrtips.netg/'
title = "Evony TKR Tips"
# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["compose", "docsy"]

copyright = 'Luke Schierer'

github_repo = "https://github.com/lschierer/EvonyTKRTips.git"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableBrowserError = true

disableKinds = []

[taxonomies]
tag = "tags"

[outputs]
  home = ["HTML", "RSS"]

[params.taxonomy]
taxonomyCloud = ["tags"] # set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloudTitle = ["Tag Cloud"] # if used, must have same length as taxonomyCloud
taxonomyPageHeader = ["tags", "terms"] # set taxonomyPageHeader = [] to hide taxonomies on the page headers

navbar_logo = true

ignoreFiles = [ "(?:^|/)OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$", "content/en/docs/doc-contributor-tools" ]

timeout = "180s"

# Highlighting config.
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

# Norwegian ("no") is sometimes but not currently used for testing.
disableLanguages = ["no"]

[caches]
 [caches.assets]
  dir = ":cacheDir/_gen"
  maxAge = -1
 [caches.getcsv]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.getjson]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.images]
  dir = ":cacheDir/_images"
  maxAge = -1
 [caches.modules]
  dir = ":cacheDir/modules"
  maxAge = -1

[markup]
 [markup.goldmark]
   [markup.goldmark.extensions]
     definitionList = true
     table = true
     typographer = false
   [markup.goldmark.parser]
     attribute = true
     autoHeadingID = true
     autoHeadingIDType = "blackfriday"
   [markup.goldmark.renderer]
     unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[frontmatter]
  date = [":git", "date", ":filename", "publishDate", "lastmod"]

[sitemap]
  filename = "sitemap.xml"
  priority = 0.75

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Fake ID in support of [params.ui.feedback]. The real GA ID is set in the Netlify config.
id = "G-9KF1R3YFTZ"

# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]


# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

[params.pushAssets]
css = [
  "callouts",
  "styles"
]
js = [
  "script"
]

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Show expand/collapse icon for sidebar sections.
sidebar_menu_foldable = true
# https://github.com/gohugoio/hugo/issues/8918#issuecomment-903314696
sidebar_cache_limit = 1
# Set to true to disable breadcrumb navigation.
breadcrumb_disable = true
taxonomy_breadcrumb_disable = true
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Language definitions.

[languages]
[languages.en]
title = "Evony TKR Tips"
description = "Tips for playing Evony TKR on a budget"
languageName = "English"
# Weight used for sorting.
weight = 1
languagedirection = "ltr"

[menu]
[[menu.main]]
  name = "About"
  url = '/'
  weight = 1
[[menu.main]]
  name = "Generals"
  url = 'generals'
  weight = 2
[[menu.main]]
  name = 'Monsters'
  url = 'monsters'
  weight = 3
[[menu.main]]
  name = 'SvS'
  url = 'svs'
  weight = 4
[[menu.main]]
  name = 'Reference'
  url = 'reference'
  weight = 5
