baseURL = 'https://evonytkrtips.netg/'
title = "Evony TKR Tips"
# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["compose"]

copyright = 'Luke Schierer'

github_repo = "https://github.com/lschierer/EvonyTKRTips.git"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableBrowserError = true

disableKinds = []

[taxonomies]
tag = "tags"

[outputs]
  home = ["HTML", "RSS"]

navbar_logo = true

ignoreFiles = [ "(?:^|/)OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$", "content/en/docs/doc-contributor-tools" ]

timeout = "180s"

# Highlighting config.
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

# Norwegian ("no") is sometimes but not currently used for testing.
disableLanguages = ["no"]

[caches]
 [caches.assets]
  dir = ":cacheDir/_gen"
  maxAge = -1
 [caches.getcsv]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.getjson]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.images]
  dir = ":cacheDir/_images"
  maxAge = -1
 [caches.modules]
  dir = ":cacheDir/modules"
  maxAge = -1

[frontmatter]
  date = [":git", "date", ":filename", "publishDate", "lastmod"]

[sitemap]
  filename = "sitemap.xml"
  priority = 0.75

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Fake ID in support of [params.ui.feedback]. The real GA ID is set in the Netlify config.
id = "G-9KF1R3YFTZ"

# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]


[params.pushAssets]
css = [
  "callouts",
  "styles"
]
js = [
  "script"
]

# Language definitions.

[languages]
[languages.en]
title = "Evony TKR Tips"
description = "Tips for playing Evony TKR on a budget"
languageName = "English"
# Weight used for sorting.
weight = 1
languagedirection = "ltr"

