[hugoVersion]
  extended = true
  min = "0.87.0"


[[mounts]]
source = 'node_modules/loadicons/'
target = 'static/loadicons/'

[[mounts]]
source = 'node_modules/lit/'
target = 'static/lit/'

[[mounts]]
source = 'node_modules/@vaadin/grid/'
target = 'static/@vaadin/grid/'

