# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = false

# robots = ""

[header]
  layout = "basic" # valid options: basic, hamburger, hybrid, custom
  # logo = "img/logo.jpg"
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, custom
  showRecent = false
  recentLimit = 5

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = false
  # sharingLinks = ["facebook", "twitter", "mastodon", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  showTaxonomies = false
  groupByYear = true
  paginationWidth = 1

[pushAssets]
  css = [
    "callouts",
	"styles"
  ]
  js = [
    "script"
  ]

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  taxonomyCloud = ["tags"] # set taxonomyCloud = [] to hide taxonomy clouds
  taxonomyCloudTitle = ["Tag Cloud"] # if used, must have same length as taxonomyCloud
  taxonomyPageHeader = ["tags", "terms"] # set taxonomyPageHeader = [] to hide taxonomies on the page headers

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[ui]
  sidebar_menu_compact = false
  sidebar_menu_foldable = true
  sidebar_cache_limit = 1
  breadcrumb_disable = true
  taxonomy_breadcrumb_disable = true
  sidebar_search_disable = false
  navbar_logo = false
  footer_about_disable = false

[ui.feadback]
  enable = false
  yes = 'Glad to hear it!'
  no = 'Sorry to hear it!'

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

